// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPC6H_VKEsDQHTlFK7hDxtKwmzBY470l0',
    appId: '1:642460479453:web:540632118d2d31e901d034',
    messagingSenderId: '642460479453',
    projectId: 'clientfittracker',
    authDomain: 'clientfittracker.firebaseapp.com',
    storageBucket: 'clientfittracker.appspot.com',
    measurementId: 'G-20ET0088X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnRDHO5_Gf2G49MBWFEI14fqOenyIieZA',
    appId: '1:642460479453:android:ae08b686f11334f101d034',
    messagingSenderId: '642460479453',
    projectId: 'clientfittracker',
    storageBucket: 'clientfittracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS1XX1arE-NAb7HgTS5JyHSaSrRWu6C1g',
    appId: '1:642460479453:ios:9b9a2f163d8b789f01d034',
    messagingSenderId: '642460479453',
    projectId: 'clientfittracker',
    storageBucket: 'clientfittracker.appspot.com',
    iosBundleId: 'com.example.clientfitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS1XX1arE-NAb7HgTS5JyHSaSrRWu6C1g',
    appId: '1:642460479453:ios:2e98be7e7b37b92001d034',
    messagingSenderId: '642460479453',
    projectId: 'clientfittracker',
    storageBucket: 'clientfittracker.appspot.com',
    iosBundleId: 'com.example.clientfitTracker.RunnerTests',
  );
}
